# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Code\AI algorithm\week3 Python高阶编程\2. PyQt使用\QtTest.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(471, 418)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 451, 301))
        self.groupBox.setObjectName("groupBox")
        self.ImageLable = QtWidgets.QLabel(self.groupBox)
        self.ImageLable.setGeometry(QtCore.QRect(30, 40, 271, 231))
        self.ImageLable.setText("")
        self.ImageLable.setObjectName("ImageLable")
        self.OpenFileBtn = QtWidgets.QPushButton(self.groupBox)
        self.OpenFileBtn.setGeometry(QtCore.QRect(330, 40, 101, 61))
        self.OpenFileBtn.setObjectName("OpenFileBtn")
        self.infolabel = QtWidgets.QLabel(self.centralwidget)
        self.infolabel.setGeometry(QtCore.QRect(10, 310, 451, 16))
        self.infolabel.setObjectName("infolabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 471, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionabout = QtWidgets.QAction(MainWindow)
        self.actionabout.setObjectName("actionabout")
        self.menu.addAction(self.actionOpen)
        self.menu.addAction(self.actionExit)
        self.menu_2.addAction(self.actionabout)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "图片浏览器"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.OpenFileBtn.setText(_translate("MainWindow", "打开文件"))
        self.infolabel.setText(_translate("MainWindow", "欢迎使用该软件"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "帮助"))
        self.actionOpen.setText(_translate("MainWindow", "打开文件"))
        self.actionExit.setText(_translate("MainWindow", "退出"))
        self.actionabout.setText(_translate("MainWindow", "关于"))
